# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160823_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.SectionHeading'),
        ),
    ]
