# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('website', '0006_auto_20160921_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_center',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_left',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_right',
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_work_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
