# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 13:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160922_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='how_we_work_center',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
