# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160823_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeammatePlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'kote',
                'verbose_name_plural': 'koteta',
            },
        ),
        migrations.DeleteModel(
            name='SectionHeading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work',
        ),
        migrations.AddField(
            model_name='teammateplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate_placement', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='teammateplacement',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Teammate'),
        ),
    ]
