# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('website', '0008_auto_20160823_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammateplacement',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='teammate',
            name='initial_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='secondary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
