# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_profilepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePage',
            new_name='ProjectPage',
        ),
    ]
