# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('website', '0012_auto_20160824_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='howweworkpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
