# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160926_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
