# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_howweworkpage_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howweworkpage',
            name='the_process_content',
            field=wagtail.wagtailcore.fields.StreamField((('process_content', wagtail.wagtailcore.blocks.StreamBlock((('title', wagtail.wagtailcore.blocks.RichTextBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
        migrations.AlterField(
            model_name='howweworkpage',
            name='what_we_do_content',
            field=wagtail.wagtailcore.fields.StreamField((('what_we_do_content', wagtail.wagtailcore.blocks.StreamBlock((('title', wagtail.wagtailcore.blocks.RichTextBlock()), ('description', wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
    ]
