# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('website', '0014_auto_20160926_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='projectopage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ProjectOPage',
        ),
    ]
