# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160926_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePage',
            new_name='ProjectPage',
        ),
    ]
