# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160926_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
