# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
