# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 12:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.RichTextBlock()),), template='streams/project_description_paragraph.html')),)),
        ),
    ]
