# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20160928_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='team_imate_secodnary',
            new_name='team_image_secondary',
        ),
    ]
