# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20160928_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='h1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='h2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
