# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20161014_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links_text', models.CharField(max_length=255)),
                ('contact_text', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
