# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 12:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_footer_footerlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLinks',
        ),
        migrations.AddField(
            model_name='footer',
            name='links',
            field=wagtail.core.fields.StreamField((('link', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.TextBlock()), ('url', wagtail.core.blocks.URLBlock())))),), default=''),
            preserve_default=False,
        ),
    ]
