# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20161030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='popup_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
