# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20170214_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(to='website.Teammate'),
        ),
    ]
