# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_blogpost_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='index_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
