# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='website.Category'),
        ),
    ]
