# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_hackcast_hackcastepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcastepisode',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
