# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_hackcast_hackcastepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcastepisode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hackcastepisode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hackcastepisode',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the episode in minutes'),
        ),
    ]
