# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('website', '0045_hackcastepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcast',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='hackcast',
            name='header_text',
            field=models.CharField(default='Shano', max_length=255),
            preserve_default=False,
        ),
    ]
