# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20180816_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(verbose_name='Post date'),
        ),
    ]
