# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_hackcastepisode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcastepisode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
