# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('website', '0046_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='header_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
