# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 11:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20180905_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howweworkpage',
            name='what_we_do_content',
            field=wagtail.core.fields.StreamField([('what_we_do_content', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.RichTextBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))]),
        ),
    ]
