# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_hackcastepisode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackcastepisode',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the episode in minutes'),
        ),
    ]
