# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('website', '0047_auto_20180910_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('index_text', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Post date')),
                ('authors', models.ManyToManyField(to='website.Teammate')),
                ('categories', models.ManyToManyField(to='website.Category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
