# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_blogpostsnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostspage',
            name='featured_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.BlogPostSnippet'),
        ),
    ]
