# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 09:03
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def migrating_to_snippet(apps, schema_editor):
  models = apps.get_model('website', 'BlogPost')
  snippet = apps.get_model('website', 'BlogPostSnippet')
  for post in models.objects.all():
      s = snippet()
      s.id = post.id
      s.title = post.title
      s.slug = slugify(post.title)
      s.cover_image = post.cover_image
      s.text = post.text
      s.index_text = post.index_text
      for author in post.authors.all():
           s.authors.add(author)
      for category in post.categories.all():
           s.categories.add(category)
      s.date = post.date
      s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20180920_0902'),
    ]

    operations = [
        migrations.RunPython(migrating_to_snippet)
    ]
