# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 11:13
from __future__ import unicode_literals

from django.db import migrations


def migrating_to_snippet(apps, schema_editor):
 models = apps.get_model('website', 'BlogPost')
 snippet = apps.get_model('website', 'BlogPostSnippet')
 for post in models.objects.all():
     s = snippet()
     s.seo_title = post.seo_title
     s.search_description = post.search_description
     s.title = post.title
     s.slug = post.slug
     s.cover_image = post.cover_image
     s.text = post.text
     s.index_text = post.index_text
     s.date = post.date
     s.save()
     for author in post.authors.all():
         s.authors.add(author)
     for category in post.categories.all():
         s.categories.add(category)



class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20180920_1111'),
    ]

    operations = [
        migrations.RunPython(migrating_to_snippet)
    ]
