# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20180920_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostplacement',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpostplacement',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='blogpostplacement',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpostsnippet_placement', to='website.BlogPostSnippet'),
        ),
    ]
