# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_auto_20180921_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsnippet',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
